# Generated by Django 5.1.7 on 2025-04-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_status',
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
