# Generated by Django 5.1.7 on 2025-04-10 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0003_user_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
    ]
