# Generated by Django 5.1.7 on 2025-04-12 17:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0004_rename_profile_pic_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Add Funds', 'Add Funds'), ('Transfer', 'Transfer'), ('Merchant Payment', 'Merchant Payment')], max_length=50)),
                ('amount', models.FloatField()),
                ('party', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='walletapp.user')),
            ],
        ),
    ]
